import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import AppFooter from "./components/shared/AppFooter";
import AppNavbar from "./components/shared/AppNavbar";
import { CartProvider } from "@/context/CardContext";

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubik.variable} antialiased  bg-[#E7E7E3] max-w-330 w-full mx-auto`}
      >
        <CartProvider>
          <AppNavbar />
          <div className="mt-22 sm:mt-30 xl:mt-36">{children}</div>
          <AppFooter />
        </CartProvider>
      </body>
    </html>
  );
}
